package:
    name: moss
    version: '0.1'
source:
    git_depth: '1'
    git_url: https://github.com/Prestipino/Moss.git
requirements:
    build:
        - python
        - setuptools
    host:
        - ca-certificates 2020.4.5.1 hecc5488_0
        - vs2015_runtime 14.16.27012 h30e32a0_2
        - vc 14.1 h869be7e_1
        - openssl 1.1.1g he774522_0
        - sqlite 3.30.1 hfa6e2cd_0
        - python 3.7.6 h60c2a47_5_cpython
        - python_abi 3.7 1_cp37m
        - wincertstore 0.2 py37_1003
        - certifi 2020.4.5.1 py37hc8dfbb8_0
        - setuptools 46.4.0 py37hc8dfbb8_0
        - wheel 0.34.2 py_1
        - pip 20.1.1 pyh9f0ad1d_0
    run:
        - python >=3.7,<3.8.0a0
        - matplotlib
        - numpy 1.18.*
        - pyqt
        - lmfit
        - python_abi 3.7.* *_cp37m
extra:
    copy_test_source_files: true
    final: true
