package:
    name: moss
    version: '0.1'
source:
    # src: /Moss/Moss
    git_depth: '1'
    git_url: https://github.com/Prestipino/Moss.git
requirements:
    build:
        - python
        - setuptools
    host:
        - python >=3.0
    run:
        - python >=3.7
        - matplotlib
        - numpy 1.11.*
        - pyqt
        - lmfit
